# Generated by Django 4.2.6 on 2023-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='places_limit',
            field=models.IntegerField(choices=[(1, '3 Places (1 Day)'), (2, '6 Places (2 Days)')], help_text='Select the limit for tourist places', verbose_name='Places Limit'),
        ),
    ]
