# Generated by Django 4.2.6 on 2023-10-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_pack_places_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='places',
        ),
    ]
