# Generated by Django 4.2.6 on 2023-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0006_remove_packages_places_remove_packages_state_and_more'),
        ('package', '0003_remove_pack_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='places',
            field=models.ManyToManyField(help_text='Select tourist places for this package', to='touristplace.touristplace', verbose_name='Tourist Places'),
        ),
    ]
