# Generated by Django 4.2.6 on 2023-10-09 18:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, unique=True, verbose_name='State Name')),
                ('description', models.TextField(help_text='Required', verbose_name='State Description')),
            ],
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, unique=True, verbose_name='Destination Name')),
                ('description', models.TextField(help_text='Required', verbose_name='Destination Description')),
                ('location', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, verbose_name='Destination Location')),
                ('state', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, verbose_name='State')),
                ('slug', models.SlugField(help_text='Required. Max length: 150 characters', max_length=150, unique=True, verbose_name='Tourist Place Slug')),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='touristplace_image')),
                ('alt_text', models.CharField(blank=True, help_text='Optional. Max length: 300 characters', max_length=300, null=True, verbose_name='Alt text')),
                ('default_image', models.BooleanField(default=False, verbose_name='Default Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('touristplace', models.ForeignKey(help_text='Choose the TouristPlace for this image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='touristplace.touristplace', verbose_name='TouristPlace')),
            ],
            options={
                'verbose_name': 'Touristplace image',
                'verbose_name_plural': 'Touristplace images',
                'ordering': ['touristplace'],
            },
        ),
    ]
