# Generated by Django 4.2.6 on 2023-10-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0002_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='state',
            field=models.ForeignKey(help_text='Required. Max length: 100 characters', on_delete=django.db.models.deletion.CASCADE, to='touristplace.state', verbose_name='State'),
        ),
    ]
