# Generated by Django 4.2.6 on 2023-10-11 14:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0004_packages_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='alt',
            field=models.CharField(blank=True, help_text='Optional. Max length: 300 characters', max_length=300, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='state_image'),
        ),
    ]
