# Generated by Django 4.2.6 on 2023-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0006_remove_packages_places_remove_packages_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
